# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: AutoRelease

on:
  push:
    branches:
      - '*'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        version: [ 10, 12 ]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo Version of ${{ matrix.os }} ${{ matrix.version }}
      - uses: actions/checkout@v3

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4

  release:
    # The type of runner that the job will run on
    needs: build
    strategy:
      matrix:
        version: [ 10, 12]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Version of ${{ matrix.os }} ${{ matrix.version }}
      - uses: actions/checkout@v3

      - name: Prepare
        run: mkdir -p output

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4

      - name: Create a file
        run: echo ${{ matrix.version }} > output/my_file.txt

      - uses: CupOfTea696/gh-action-auto-release@v1.0.0
        if: matrix.version == 10
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Upload ${{ matrix.os }} ${{ matrix.version }}
        uses: actions/upload-artifact@v3
        with:
          name: output-rpms ${{ matrix.os }} ${{ matrix.version }}
          path: output/my_file.txt
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
