# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: AutoRelease

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        version: [ 10, 12]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo Version of ${{ matrix.os }} ${{ matrix.version }}
      - uses: actions/checkout@v3

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4

      - uses: actions/upload-artifact@v2
        with:
          path: build/*.tar.gz
          name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz

  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^Release: #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
