# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: AutoRelease

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        version: [ 10]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo Version of ${{ matrix.os }} ${{ matrix.version }}
      - uses: actions/checkout@v3

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4

      - uses: actions/upload-artifact@v2
        with:
          path: build/*.tar.gz
          name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo ${{ secrets.GITHUB_TOKEN }}
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
