# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: AutoRelease

on: [push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        version: [ 10, 12 ]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo Version of ${{ matrix.os }} ${{ matrix.version }}
      - uses: actions/checkout@v3

      - name: Prepare release
        if: contains(github.ref, 'refs/tags/')
        run: mkdir -p output

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4

      - name: Create a file
        if: contains(github.ref, 'refs/tags/')
        run: echo ${{ matrix.version }} output/${{ matrix.version }}_my_file.txt

      - name: Upload RPM "${{ matrix.arch }}"
        if: contains(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: rpm-${{ matrix.arch }}
          path: output


  release:
    # The type of runner that the job will run on
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Create a release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: This release was autogenerated.
          files: '*.txt'
